### ISSUE TITLE
(Request) A more generic string when entering a URL

### ISSUE THREAD

**Issue by llakala** [crllect/Cryphr#2]
When entering a link, the current string of text that appears on an empty link is: "Enter URL here". However, this isn't just friendly to URLs, as I assumed. It also allows searching the web, which I only realized after reading through the settings. If the text was changed to something like: "Search with {searchEngine} here", with the user's chosen search engine concatenated into the string, it would be clearer to the user.

**Comment by Mazedotexe** [comment]
Interesting, but your suggestion "Search with {searchEngine} here" would kind of imply that it's _not_ URL friendly, resulting in the opposite problem. I think it would be best to compromise with "Search the web or enter URL here," like I'm fairly sure Google did. Also, with changes that small, why not make a PR instead of an issue?

**Comment by crllect** [comment]
This project isn't at the top of my todo list, however if or when I update it, I will fix css imports not working, and apply some of the suggestions in issues

**Comment by llakala** [comment]
> Interesting, but your suggestion "Search with {searchEngine} here" would kind of imply that it's _not_ URL friendly, resulting in the opposite problem. I think it would be best to compromise with "Search the web or enter URL here," like I'm fairly sure Google did. Also, with changes that small, why not make a PR instead of an issue?

Good point, I'll make a PR!

**Comment by llakala** [comment]
Fixed after PR merging!
